FROM php:7-fpm
ENV COMPOSER_VERSION master
RUN apt-get update && apt-get install -y git 
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


